email_crud&validate
InnaKuts/pre-pre-beta-siri pull request #12
Opened 2024-08-14 17:57 UTC by Dasha-lev

Added functions to add, change, delete & validate emails

2024-08-14 18:02 UTC, InnaKuts commented
My congratulations 🙌 🥳 🎉

2024-08-14 18:45 UTC, InnaKuts commented on main.py
> +from tools.decorators import command_check_decorator, parse_input_validator
тут помилка. має бути
`from tools import command_check_decorator, parse_input_validator`

2024-08-14 18:45 UTC, InnaKuts commented on main.py
> +def email_validator(func):
Бажано ці функції перенести в окремий файл а не в main тримати. Гарне місце було би tools/address_book_functions.py але там і так уже багато. Варто окремий файл зробити для цих функцій тоді і конфліктів не буде з іншими змінами. Це стосується всіх доданих функцій

2024-08-14 18:45 UTC, InnaKuts commented on main.py
> +    session = PromptSession(completer=CommandCompleter(commands))
ця зміна не зовсім належить до задачі і до коміту але зміна правильна. Плюсую

2024-08-14 18:45 UTC, InnaKuts commented on main.py
> +def email_validator(func):
Ще важливий момент - не вистачає функції по роботі з імейлом в самому класі Record. Ось приклад

<img width="579" alt="Screenshot 2024-08-14 at 20 44 28" src="https://github.com/user-attachments/assets/9b319299-28ae-4940-bf67-80e9dedf3a6f">

2024-08-15 11:03 UTC, kgrebets commented
На майбутнє: коли починаєш працювати над фічою то краще робити це у гілці
feature/[feature-name]. Feature/email у твоємо випадку. Так буде консистентно. Плюс якщо є багфікси чи релізи вони теж в окремих групах (bugfix/  або release/)

2024-08-15 11:05 UTC, Dasha-lev commented on main.py
> +from tools.decorators import command_check_decorator, parse_input_validator
changed

2024-08-15 11:05 UTC, Dasha-lev commented on main.py
> +def email_validator(func):
не зовсім зрозуміла що треба зробити. всі функції перенести в окремий файл?

2024-08-15 11:18 UTC, kgrebets requested changes, later dismissed
Головне виправити class Record:

2024-08-15 11:18 UTC, kgrebets commented on main.py
> +class Record:
І класс Record у нас є (model/record.py) треба свої зміни в нього додати, а тут клас не потрібен

2024-08-15 11:18 UTC, kgrebets commented on main.py
> +        "add-email": add_email,  # New command for adding email
Мінорно: Технічно назва самої дії це і є комнтар і він тут не потрбен. Плюс "New command" він буде тільки до часу поки не змерджатся зміни

2024-08-15 12:21 UTC, InnaKuts commented on main.py
> +def email_validator(func):
@kgrebets нижче підмітив - треба функції в існуючий клас Record дописати, щоб він умів робити edit_email (і інші функції). Бо тут ти викликаєш функцію цього класу а вона не реалізована

2024-08-15 16:39 UTC, InnaKuts commented
@Dasha-lev я зарезолвила конфлікти з мейном і пофіксила запуск програми та додавання імейлу - в останньому коміті деталі
@kgrebets як буде можливість, рев"ювни знову

2024-08-15 18:49 UTC, InnaKuts approved these changes, later dismissed

2024-08-16 06:58 UTC, kgrebets commented on main.py
> +def email_validator(func):
@Dasha-lev зможеш ці функції в окремий файл винести?

2024-08-16 09:21 UTC, merged